pub mod battery;
pub mod cleaner;
pub mod connections;
pub mod dev_tools;
pub mod disks;
pub mod git_radar;
pub mod hosts_manager;
pub mod latency;
pub mod machine_info;
pub mod obsidian;
pub mod processes;
pub mod sniffer;
pub mod speedtest;
pub mod traffic;
pub mod updater;

pub use battery::BatteryCollector;
pub use cleaner::SystemCleaner;
pub use connections::ConnectionsCollector;
pub use dev_tools::DevToolsCollector;
pub use disks::DiskCollector;
pub use git_radar::GitRadar;
pub use hosts_manager::HostsManager;
pub use latency::LatencyCollector;
pub use machine_info::MachineInfoCollector;
pub use obsidian::ObsidianManager;
pub use processes::{kill_process, kill_process_by_port, ProcessCollector};
pub use sniffer::start_sniffer;
pub use speedtest::SpeedTester;
pub use traffic::TrafficCollector;
pub use updater::AutoUpdater;

